export const allInterests = [
  "Cooking / Baking",
  "Gaming",
  "Reading",
  "Health & Fitness",
  "Sports",
  "Travelling",
  "DIY",
  "Film & Movies",
  "Drawing",
  "Painting",
  "Music",
  "Dance",
  "Technology",
  "Cars / Vehicles",
  "Shopping",
  "Partying",
  "Animals & Wildlife",
  "Writing",
];
